import { Question } from "@/types/question";

export const sampleQuestions: Question[] = [
  {
    id: 1,
    subject: "História",
    topic: "Brasil Império",
    difficulty: "easy",
    banca: "FGV",
    year: 2023,
    cargo: "Analista",
    instituicao: "IBGE",
    title: "Independência do Brasil",
    text: "Em que ano ocorreu a Independência do Brasil?",
    options: [
      { letter: "A", text: "1889" },
      { letter: "B", text: "1822" },
      { letter: "C", text: "1500" },
      { letter: "D", text: "1789" },
    ],
    correctAnswer: "B",
  },
  {
    id: 2,
    subject: "Português",
    topic: "Gramática",
    difficulty: "medium",
    banca: "CESPE",
    year: 2022,
    cargo: "Técnico",
    instituicao: "TCU",
    title: "Concordância Verbal",
    text: "Qual das alternativas apresenta concordância verbal correta?",
    options: [
      { letter: "A", text: "Fazem dois anos que não o vejo." },
      { letter: "B", text: "Houveram muitos acidentes na estrada." },
      { letter: "C", text: "Existem várias possibilidades de solução." },
      { letter: "D", text: "Haviam pessoas esperando na fila." },
    ],
    correctAnswer: "C",
  },
  {
    id: 3,
    subject: "Matemática",
    topic: "Porcentagem",
    difficulty: "easy",
    banca: "FCC",
    year: 2023,
    cargo: "Auditor",
    instituicao: "TRT",
    title: "Cálculo de Porcentagem",
    text: "Um produto que custava R$ 200,00 teve um aumento de 15%. Qual o novo preço?",
    options: [
      { letter: "A", text: "R$ 215,00" },
      { letter: "B", text: "R$ 230,00" },
      { letter: "C", text: "R$ 225,00" },
      { letter: "D", text: "R$ 220,00" },
    ],
    correctAnswer: "B",
  },
  {
    id: 4,
    subject: "Direito Constitucional",
    topic: "Direitos Fundamentais",
    difficulty: "medium",
    banca: "VUNESP",
    year: 2022,
    cargo: "Procurador",
    instituicao: "PGE",
    title: "Direitos e Garantias",
    text: "De acordo com a Constituição Federal, o habeas corpus será concedido:",
    options: [
      { letter: "A", text: "Sempre que alguém sofrer violação de direito líquido e certo." },
      { letter: "B", text: "Sempre que alguém sofrer ou se achar ameaçado de sofrer violência ou coação em sua liberdade de locomoção." },
      { letter: "C", text: "Para proteger direito líquido e certo não amparado por habeas data." },
      { letter: "D", text: "Para anular ato lesivo ao patrimônio público." },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    subject: "Raciocínio Lógico",
    topic: "Proposições",
    difficulty: "hard",
    banca: "CEBRASPE",
    year: 2023,
    cargo: "Analista",
    instituicao: "MPU",
    title: "Lógica Proposicional",
    text: "Se a proposição 'Se chove, então a rua fica molhada' é verdadeira e 'A rua não está molhada' é verdadeira, então:",
    options: [
      { letter: "A", text: "Está chovendo." },
      { letter: "B", text: "Não está chovendo." },
      { letter: "C", text: "A rua está molhada." },
      { letter: "D", text: "Não é possível determinar." },
    ],
    correctAnswer: "B",
  },
  {
    id: 6,
    subject: "Geografia",
    topic: "Brasil - Regiões",
    difficulty: "easy",
    banca: "FCC",
    year: 2023,
    cargo: "Técnico",
    instituicao: "IBGE",
    title: "Regiões do Brasil",
    text: "Qual é a maior região do Brasil em extensão territorial?",
    options: [
      { letter: "A", text: "Sudeste" },
      { letter: "B", text: "Nordeste" },
      { letter: "C", text: "Norte" },
      { letter: "D", text: "Centro-Oeste" },
    ],
    correctAnswer: "C",
  },
  {
    id: 7,
    subject: "Português",
    topic: "Interpretação de Texto",
    difficulty: "medium",
    banca: "CESPE",
    year: 2022,
    cargo: "Analista",
    instituicao: "STF",
    title: "Coesão Textual",
    text: "Na frase 'João estudou muito, por isso foi aprovado', a expressão 'por isso' estabelece uma relação de:",
    options: [
      { letter: "A", text: "Causa" },
      { letter: "B", text: "Consequência" },
      { letter: "C", text: "Condição" },
      { letter: "D", text: "Concessão" },
    ],
    correctAnswer: "B",
  },
  {
    id: 8,
    subject: "Matemática",
    topic: "Equações",
    difficulty: "medium",
    banca: "FGV",
    year: 2023,
    cargo: "Analista",
    instituicao: "Banco Central",
    title: "Equação do 1º Grau",
    text: "Qual o valor de x na equação 3x + 7 = 22?",
    options: [
      { letter: "A", text: "x = 3" },
      { letter: "B", text: "x = 5" },
      { letter: "C", text: "x = 7" },
      { letter: "D", text: "x = 4" },
    ],
    correctAnswer: "B",
  },
  {
    id: 9,
    subject: "Direito Administrativo",
    topic: "Atos Administrativos",
    difficulty: "hard",
    banca: "CESPE",
    year: 2022,
    cargo: "Procurador",
    instituicao: "AGU",
    title: "Atributos dos Atos",
    text: "São atributos do ato administrativo, EXCETO:",
    options: [
      { letter: "A", text: "Presunção de legitimidade" },
      { letter: "B", text: "Autoexecutoriedade" },
      { letter: "C", text: "Tipicidade" },
      { letter: "D", text: "Bilateralidade" },
    ],
    correctAnswer: "D",
  },
  {
    id: 10,
    subject: "História",
    topic: "Brasil República",
    difficulty: "medium",
    banca: "VUNESP",
    year: 2023,
    cargo: "Professor",
    instituicao: "SEE-SP",
    title: "Era Vargas",
    text: "O Estado Novo, período da ditadura de Getúlio Vargas, durou de:",
    options: [
      { letter: "A", text: "1930 a 1945" },
      { letter: "B", text: "1937 a 1945" },
      { letter: "C", text: "1934 a 1937" },
      { letter: "D", text: "1945 a 1964" },
    ],
    correctAnswer: "B",
  },
  {
    id: 11,
    subject: "Informática",
    topic: "Hardware",
    difficulty: "easy",
    banca: "FCC",
    year: 2023,
    cargo: "Técnico",
    instituicao: "TRE",
    title: "Componentes do Computador",
    text: "Qual componente é responsável pelo processamento de dados em um computador?",
    options: [
      { letter: "A", text: "HD" },
      { letter: "B", text: "Memória RAM" },
      { letter: "C", text: "CPU" },
      { letter: "D", text: "Placa de vídeo" },
    ],
    correctAnswer: "C",
  },
  {
    id: 12,
    subject: "Raciocínio Lógico",
    topic: "Sequências",
    difficulty: "easy",
    banca: "FGV",
    year: 2022,
    cargo: "Assistente",
    instituicao: "SEFAZ",
    title: "Sequência Numérica",
    text: "Qual o próximo número da sequência: 2, 4, 8, 16, __?",
    options: [
      { letter: "A", text: "20" },
      { letter: "B", text: "24" },
      { letter: "C", text: "32" },
      { letter: "D", text: "30" },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    subject: "Português",
    topic: "Ortografia",
    difficulty: "easy",
    banca: "CESPE",
    year: 2023,
    cargo: "Técnico",
    instituicao: "INSS",
    title: "Grafia Correta",
    text: "Qual palavra está escrita corretamente?",
    options: [
      { letter: "A", text: "Excessão" },
      { letter: "B", text: "Exceção" },
      { letter: "C", text: "Exeção" },
      { letter: "D", text: "Excesão" },
    ],
    correctAnswer: "B",
  },
  {
    id: 14,
    subject: "Direito Constitucional",
    topic: "Organização do Estado",
    difficulty: "medium",
    banca: "FCC",
    year: 2022,
    cargo: "Analista",
    instituicao: "TRF",
    title: "Poderes da União",
    text: "São Poderes da União, independentes e harmônicos entre si:",
    options: [
      { letter: "A", text: "Legislativo, Executivo e Judiciário" },
      { letter: "B", text: "Federal, Estadual e Municipal" },
      { letter: "C", text: "Legislativo, Administrativo e Judiciário" },
      { letter: "D", text: "Executivo, Consultivo e Legislativo" },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    subject: "Matemática",
    topic: "Geometria",
    difficulty: "medium",
    banca: "VUNESP",
    year: 2023,
    cargo: "Engenheiro",
    instituicao: "SABESP",
    title: "Área do Triângulo",
    text: "Qual a área de um triângulo com base 10cm e altura 6cm?",
    options: [
      { letter: "A", text: "60 cm²" },
      { letter: "B", text: "30 cm²" },
      { letter: "C", text: "16 cm²" },
      { letter: "D", text: "40 cm²" },
    ],
    correctAnswer: "B",
  },
  {
    id: 16,
    subject: "Geografia",
    topic: "Climatologia",
    difficulty: "medium",
    banca: "CESPE",
    year: 2022,
    cargo: "Analista",
    instituicao: "IBAMA",
    title: "Clima Brasileiro",
    text: "O clima predominante na região Amazônica é:",
    options: [
      { letter: "A", text: "Tropical de altitude" },
      { letter: "B", text: "Equatorial úmido" },
      { letter: "C", text: "Subtropical" },
      { letter: "D", text: "Semiárido" },
    ],
    correctAnswer: "B",
  },
  {
    id: 17,
    subject: "Informática",
    topic: "Software",
    difficulty: "easy",
    banca: "FGV",
    year: 2023,
    cargo: "Assistente",
    instituicao: "Prefeitura",
    title: "Sistema Operacional",
    text: "Qual destes é um sistema operacional?",
    options: [
      { letter: "A", text: "Microsoft Word" },
      { letter: "B", text: "Google Chrome" },
      { letter: "C", text: "Windows 11" },
      { letter: "D", text: "Adobe Photoshop" },
    ],
    correctAnswer: "C",
  },
  {
    id: 18,
    subject: "Direito Penal",
    topic: "Crimes",
    difficulty: "hard",
    banca: "CESPE",
    year: 2022,
    cargo: "Delegado",
    instituicao: "Polícia Civil",
    title: "Excludentes de Ilicitude",
    text: "NÃO é causa excludente de ilicitude:",
    options: [
      { letter: "A", text: "Legítima defesa" },
      { letter: "B", text: "Estado de necessidade" },
      { letter: "C", text: "Exercício regular de direito" },
      { letter: "D", text: "Culpabilidade" },
    ],
    correctAnswer: "D",
  },
  {
    id: 19,
    subject: "História",
    topic: "História Geral",
    difficulty: "easy",
    banca: "FCC",
    year: 2023,
    cargo: "Professor",
    instituicao: "SME",
    title: "Segunda Guerra Mundial",
    text: "Em que ano terminou a Segunda Guerra Mundial?",
    options: [
      { letter: "A", text: "1939" },
      { letter: "B", text: "1942" },
      { letter: "C", text: "1945" },
      { letter: "D", text: "1950" },
    ],
    correctAnswer: "C",
  },
  {
    id: 20,
    subject: "Português",
    topic: "Figuras de Linguagem",
    difficulty: "medium",
    banca: "VUNESP",
    year: 2022,
    cargo: "Analista",
    instituicao: "ALESP",
    title: "Metáfora",
    text: "Na frase 'A vida é uma viagem', temos uma:",
    options: [
      { letter: "A", text: "Metonímia" },
      { letter: "B", text: "Metáfora" },
      { letter: "C", text: "Hipérbole" },
      { letter: "D", text: "Ironia" },
    ],
    correctAnswer: "B",
  },
  {
    id: 21,
    subject: "Matemática",
    topic: "Razão e Proporção",
    difficulty: "medium",
    banca: "FGV",
    year: 2023,
    cargo: "Auditor",
    instituicao: "CGU",
    title: "Regra de Três",
    text: "Se 5 operários constroem um muro em 8 dias, em quantos dias 10 operários construirão o mesmo muro?",
    options: [
      { letter: "A", text: "16 dias" },
      { letter: "B", text: "4 dias" },
      { letter: "C", text: "10 dias" },
      { letter: "D", text: "2 dias" },
    ],
    correctAnswer: "B",
  },
  {
    id: 22,
    subject: "Raciocínio Lógico",
    topic: "Conjuntos",
    difficulty: "medium",
    banca: "CESPE",
    year: 2022,
    cargo: "Técnico",
    instituicao: "BACEN",
    title: "Operações com Conjuntos",
    text: "Se A = {1, 2, 3} e B = {2, 3, 4}, qual é A ∩ B?",
    options: [
      { letter: "A", text: "{1, 2, 3, 4}" },
      { letter: "B", text: "{2, 3}" },
      { letter: "C", text: "{1, 4}" },
      { letter: "D", text: "{1}" },
    ],
    correctAnswer: "B",
  },
  {
    id: 23,
    subject: "Direito Trabalhista",
    topic: "CLT",
    difficulty: "medium",
    banca: "FCC",
    year: 2023,
    cargo: "Analista",
    instituicao: "TRT",
    title: "Férias",
    text: "Após quantos meses de trabalho o empregado adquire direito a férias?",
    options: [
      { letter: "A", text: "6 meses" },
      { letter: "B", text: "12 meses" },
      { letter: "C", text: "18 meses" },
      { letter: "D", text: "24 meses" },
    ],
    correctAnswer: "B",
  },
  {
    id: 24,
    subject: "Geografia",
    topic: "Geopolítica",
    difficulty: "hard",
    banca: "VUNESP",
    year: 2022,
    cargo: "Diplomata",
    instituicao: "MRE",
    title: "BRICS",
    text: "Quais países formavam originalmente o grupo BRICS?",
    options: [
      { letter: "A", text: "Brasil, Rússia, Índia, China e África do Sul" },
      { letter: "B", text: "Brasil, Rússia, Itália, China e Suíça" },
      { letter: "C", text: "Bolívia, Rússia, Índia, Canadá e Suécia" },
      { letter: "D", text: "Brasil, Romênia, Irlanda, China e Sérvia" },
    ],
    correctAnswer: "A",
  },
  {
    id: 25,
    subject: "Informática",
    topic: "Internet",
    difficulty: "easy",
    banca: "CESPE",
    year: 2023,
    cargo: "Assistente",
    instituicao: "ANATEL",
    title: "Navegadores",
    text: "Qual destes NÃO é um navegador de internet?",
    options: [
      { letter: "A", text: "Google Chrome" },
      { letter: "B", text: "Mozilla Firefox" },
      { letter: "C", text: "Microsoft Excel" },
      { letter: "D", text: "Microsoft Edge" },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    subject: "Português",
    topic: "Acentuação",
    difficulty: "easy",
    banca: "FGV",
    year: 2022,
    cargo: "Técnico",
    instituicao: "SEFAZ",
    title: "Regras de Acentuação",
    text: "Qual palavra é acentuada por ser proparoxítona?",
    options: [
      { letter: "A", text: "Café" },
      { letter: "B", text: "Lâmpada" },
      { letter: "C", text: "Táxi" },
      { letter: "D", text: "Você" },
    ],
    correctAnswer: "B",
  },
  {
    id: 27,
    subject: "Matemática",
    topic: "Estatística",
    difficulty: "medium",
    banca: "FCC",
    year: 2023,
    cargo: "Estatístico",
    instituicao: "IBGE",
    title: "Média Aritmética",
    text: "Qual a média aritmética de 4, 6, 8, 10 e 12?",
    options: [
      { letter: "A", text: "7" },
      { letter: "B", text: "8" },
      { letter: "C", text: "9" },
      { letter: "D", text: "10" },
    ],
    correctAnswer: "B",
  },
  {
    id: 28,
    subject: "Direito Civil",
    topic: "Pessoas",
    difficulty: "medium",
    banca: "CESPE",
    year: 2022,
    cargo: "Juiz",
    instituicao: "TJ",
    title: "Capacidade Civil",
    text: "A capacidade civil plena é adquirida aos:",
    options: [
      { letter: "A", text: "16 anos" },
      { letter: "B", text: "18 anos" },
      { letter: "C", text: "21 anos" },
      { letter: "D", text: "25 anos" },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    subject: "História",
    topic: "Brasil Colônia",
    difficulty: "easy",
    banca: "VUNESP",
    year: 2023,
    cargo: "Professor",
    instituicao: "SEDUC",
    title: "Descobrimento",
    text: "Quem comandou a expedição que chegou ao Brasil em 1500?",
    options: [
      { letter: "A", text: "Cristóvão Colombo" },
      { letter: "B", text: "Pedro Álvares Cabral" },
      { letter: "C", text: "Vasco da Gama" },
      { letter: "D", text: "Fernão de Magalhães" },
    ],
    correctAnswer: "B",
  },
  {
    id: 30,
    subject: "Raciocínio Lógico",
    topic: "Probabilidade",
    difficulty: "hard",
    banca: "FGV",
    year: 2022,
    cargo: "Analista",
    instituicao: "BNDES",
    title: "Cálculo de Probabilidade",
    text: "Qual a probabilidade de obter cara ao lançar uma moeda honesta duas vezes consecutivas?",
    options: [
      { letter: "A", text: "1/2" },
      { letter: "B", text: "1/4" },
      { letter: "C", text: "3/4" },
      { letter: "D", text: "1/3" },
    ],
    correctAnswer: "B",
  },
];

export const getQuestionsBySubject = (subject: string, count: number): Question[] => {
  let filtered = subject === "Todas" 
    ? [...sampleQuestions] 
    : sampleQuestions.filter(q => q.subject === subject);
  
  // Shuffle and return requested count
  const shuffled = filtered.sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
};

export const calculateXP = (isCorrect: boolean, confidence: "certeza" | "duvida" | "chute"): number => {
  if (!isCorrect) return 0;
  
  switch (confidence) {
    case "certeza": return 5;
    case "duvida": return 3;
    case "chute": return 1;
    default: return 0;
  }
};
