import { Question } from "@/types/question";

export const sampleQuestions: Question[] = [
  {
    id: 1,
    subject: "História",
    topic: "Brasil Império",
    difficulty: "easy",
    banca: "FGV",
    year: 2023,
    cargo: "Analista",
    instituicao: "IBGE",
    title: "Independência do Brasil",
    text: "Em que ano ocorreu a Independência do Brasil?",
    options: [
      { letter: "A", text: "1889" },
      { letter: "B", text: "1822" },
      { letter: "C", text: "1500" },
      { letter: "D", text: "1789" },
    ],
    correctAnswer: "B",
  },
  {
    id: 2,
    subject: "Português",
    topic: "Gramática",
    difficulty: "medium",
    banca: "CESPE",
    year: 2022,
    cargo: "Técnico",
    instituicao: "TCU",
    title: "Concordância Verbal",
    text: "Qual das alternativas apresenta concordância verbal correta?",
    options: [
      { letter: "A", text: "Fazem dois anos que não o vejo." },
      { letter: "B", text: "Houveram muitos acidentes na estrada." },
      { letter: "C", text: "Existem várias possibilidades de solução." },
      { letter: "D", text: "Haviam pessoas esperando na fila." },
    ],
    correctAnswer: "C",
  },
  {
    id: 3,
    subject: "Matemática",
    topic: "Porcentagem",
    difficulty: "easy",
    banca: "FCC",
    year: 2023,
    cargo: "Auditor",
    instituicao: "TRT",
    title: "Cálculo de Porcentagem",
    text: "Um produto que custava R$ 200,00 teve um aumento de 15%. Qual o novo preço?",
    options: [
      { letter: "A", text: "R$ 215,00" },
      { letter: "B", text: "R$ 230,00" },
      { letter: "C", text: "R$ 225,00" },
      { letter: "D", text: "R$ 220,00" },
    ],
    correctAnswer: "B",
  },
  {
    id: 4,
    subject: "Direito Constitucional",
    topic: "Direitos Fundamentais",
    difficulty: "medium",
    banca: "VUNESP",
    year: 2022,
    cargo: "Procurador",
    instituicao: "PGE",
    title: "Direitos e Garantias",
    text: "De acordo com a Constituição Federal, o habeas corpus será concedido:",
    options: [
      { letter: "A", text: "Sempre que alguém sofrer violação de direito líquido e certo." },
      { letter: "B", text: "Sempre que alguém sofrer ou se achar ameaçado de sofrer violência ou coação em sua liberdade de locomoção." },
      { letter: "C", text: "Para proteger direito líquido e certo não amparado por habeas data." },
      { letter: "D", text: "Para anular ato lesivo ao patrimônio público." },
    ],
    correctAnswer: "B",
  },
  {
    id: 5,
    subject: "Raciocínio Lógico",
    topic: "Proposições",
    difficulty: "hard",
    banca: "CEBRASPE",
    year: 2023,
    cargo: "Analista",
    instituicao: "MPU",
    title: "Lógica Proposicional",
    text: "Se a proposição 'Se chove, então a rua fica molhada' é verdadeira e 'A rua não está molhada' é verdadeira, então:",
    options: [
      { letter: "A", text: "Está chovendo." },
      { letter: "B", text: "Não está chovendo." },
      { letter: "C", text: "A rua está molhada." },
      { letter: "D", text: "Não é possível determinar." },
    ],
    correctAnswer: "B",
  },
  {
    id: 6,
    subject: "Geografia",
    topic: "Brasil - Regiões",
    difficulty: "easy",
    banca: "FCC",
    year: 2023,
    cargo: "Técnico",
    instituicao: "IBGE",
    title: "Regiões do Brasil",
    text: "Qual é a maior região do Brasil em extensão territorial?",
    options: [
      { letter: "A", text: "Sudeste" },
      { letter: "B", text: "Nordeste" },
      { letter: "C", text: "Norte" },
      { letter: "D", text: "Centro-Oeste" },
    ],
    correctAnswer: "C",
  },
  {
    id: 7,
    subject: "Português",
    topic: "Interpretação de Texto",
    difficulty: "medium",
    banca: "CESPE",
    year: 2022,
    cargo: "Analista",
    instituicao: "STF",
    title: "Coesão Textual",
    text: "Na frase 'João estudou muito, por isso foi aprovado', a expressão 'por isso' estabelece uma relação de:",
    options: [
      { letter: "A", text: "Causa" },
      { letter: "B", text: "Consequência" },
      { letter: "C", text: "Condição" },
      { letter: "D", text: "Concessão" },
    ],
    correctAnswer: "B",
  },
  {
    id: 8,
    subject: "Matemática",
    topic: "Equações",
    difficulty: "medium",
    banca: "FGV",
    year: 2023,
    cargo: "Analista",
    instituicao: "Banco Central",
    title: "Equação do 1º Grau",
    text: "Qual o valor de x na equação 3x + 7 = 22?",
    options: [
      { letter: "A", text: "x = 3" },
      { letter: "B", text: "x = 5" },
      { letter: "C", text: "x = 7" },
      { letter: "D", text: "x = 4" },
    ],
    correctAnswer: "B",
  },
  {
    id: 9,
    subject: "Direito Administrativo",
    topic: "Atos Administrativos",
    difficulty: "hard",
    banca: "CESPE",
    year: 2022,
    cargo: "Procurador",
    instituicao: "AGU",
    title: "Atributos dos Atos",
    text: "São atributos do ato administrativo, EXCETO:",
    options: [
      { letter: "A", text: "Presunção de legitimidade" },
      { letter: "B", text: "Autoexecutoriedade" },
      { letter: "C", text: "Tipicidade" },
      { letter: "D", text: "Bilateralidade" },
    ],
    correctAnswer: "D",
  },
  {
    id: 10,
    subject: "História",
    topic: "Brasil República",
    difficulty: "medium",
    banca: "VUNESP",
    year: 2023,
    cargo: "Professor",
    instituicao: "SEE-SP",
    title: "Era Vargas",
    text: "O Estado Novo, período da ditadura de Getúlio Vargas, durou de:",
    options: [
      { letter: "A", text: "1930 a 1945" },
      { letter: "B", text: "1937 a 1945" },
      { letter: "C", text: "1934 a 1937" },
      { letter: "D", text: "1945 a 1964" },
    ],
    correctAnswer: "B",
  },
  {
    id: 11,
    subject: "Informática",
    topic: "Hardware",
    difficulty: "easy",
    banca: "FCC",
    year: 2023,
    cargo: "Técnico",
    instituicao: "TRE",
    title: "Componentes do Computador",
    text: "Qual componente é responsável pelo processamento de dados em um computador?",
    options: [
      { letter: "A", text: "HD" },
      { letter: "B", text: "Memória RAM" },
      { letter: "C", text: "CPU" },
      { letter: "D", text: "Placa de vídeo" },
    ],
    correctAnswer: "C",
  },
  {
    id: 12,
    subject: "Raciocínio Lógico",
    topic: "Sequências",
    difficulty: "easy",
    banca: "FGV",
    year: 2022,
    cargo: "Assistente",
    instituicao: "SEFAZ",
    title: "Sequência Numérica",
    text: "Qual o próximo número da sequência: 2, 4, 8, 16, __?",
    options: [
      { letter: "A", text: "20" },
      { letter: "B", text: "24" },
      { letter: "C", text: "32" },
      { letter: "D", text: "30" },
    ],
    correctAnswer: "C",
  },
  {
    id: 13,
    subject: "Português",
    topic: "Ortografia",
    difficulty: "easy",
    banca: "CESPE",
    year: 2023,
    cargo: "Técnico",
    instituicao: "INSS",
    title: "Grafia Correta",
    text: "Qual palavra está escrita corretamente?",
    options: [
      { letter: "A", text: "Excessão" },
      { letter: "B", text: "Exceção" },
      { letter: "C", text: "Exeção" },
      { letter: "D", text: "Excesão" },
    ],
    correctAnswer: "B",
  },
  {
    id: 14,
    subject: "Direito Constitucional",
    topic: "Organização do Estado",
    difficulty: "medium",
    banca: "FCC",
    year: 2022,
    cargo: "Analista",
    instituicao: "TRF",
    title: "Poderes da União",
    text: "São Poderes da União, independentes e harmônicos entre si:",
    options: [
      { letter: "A", text: "Legislativo, Executivo e Judiciário" },
      { letter: "B", text: "Federal, Estadual e Municipal" },
      { letter: "C", text: "Legislativo, Administrativo e Judiciário" },
      { letter: "D", text: "Executivo, Consultivo e Legislativo" },
    ],
    correctAnswer: "A",
  },
  {
    id: 15,
    subject: "Matemática",
    topic: "Geometria",
    difficulty: "medium",
    banca: "VUNESP",
    year: 2023,
    cargo: "Engenheiro",
    instituicao: "SABESP",
    title: "Área do Triângulo",
    text: "Qual a área de um triângulo com base 10cm e altura 6cm?",
    options: [
      { letter: "A", text: "60 cm²" },
      { letter: "B", text: "30 cm²" },
      { letter: "C", text: "16 cm²" },
      { letter: "D", text: "40 cm²" },
    ],
    correctAnswer: "B",
  },
  {
    id: 16,
    subject: "Geografia",
    topic: "Climatologia",
    difficulty: "medium",
    banca: "CESPE",
    year: 2022,
    cargo: "Analista",
    instituicao: "IBAMA",
    title: "Clima Brasileiro",
    text: "O clima predominante na região Amazônica é:",
    options: [
      { letter: "A", text: "Tropical de altitude" },
      { letter: "B", text: "Equatorial úmido" },
      { letter: "C", text: "Subtropical" },
      { letter: "D", text: "Semiárido" },
    ],
    correctAnswer: "B",
  },
  {
    id: 17,
    subject: "Informática",
    topic: "Software",
    difficulty: "easy",
    banca: "FGV",
    year: 2023,
    cargo: "Assistente",
    instituicao: "Prefeitura",
    title: "Sistema Operacional",
    text: "Qual destes é um sistema operacional?",
    options: [
      { letter: "A", text: "Microsoft Word" },
      { letter: "B", text: "Google Chrome" },
      { letter: "C", text: "Windows 11" },
      { letter: "D", text: "Adobe Photoshop" },
    ],
    correctAnswer: "C",
  },
  {
    id: 18,
    subject: "Direito Penal",
    topic: "Crimes",
    difficulty: "hard",
    banca: "CESPE",
    year: 2022,
    cargo: "Delegado",
    instituicao: "Polícia Civil",
    title: "Excludentes de Ilicitude",
    text: "NÃO é causa excludente de ilicitude:",
    options: [
      { letter: "A", text: "Legítima defesa" },
      { letter: "B", text: "Estado de necessidade" },
      { letter: "C", text: "Exercício regular de direito" },
      { letter: "D", text: "Culpabilidade" },
    ],
    correctAnswer: "D",
  },
  {
    id: 19,
    subject: "História",
    topic: "História Geral",
    difficulty: "easy",
    banca: "FCC",
    year: 2023,
    cargo: "Professor",
    instituicao: "SME",
    title: "Segunda Guerra Mundial",
    text: "Em que ano terminou a Segunda Guerra Mundial?",
    options: [
      { letter: "A", text: "1939" },
      { letter: "B", text: "1942" },
      { letter: "C", text: "1945" },
      { letter: "D", text: "1950" },
    ],
    correctAnswer: "C",
  },
  {
    id: 20,
    subject: "Português",
    topic: "Figuras de Linguagem",
    difficulty: "medium",
    banca: "VUNESP",
    year: 2022,
    cargo: "Analista",
    instituicao: "ALESP",
    title: "Metáfora",
    text: "Na frase 'A vida é uma viagem', temos uma:",
    options: [
      { letter: "A", text: "Metonímia" },
      { letter: "B", text: "Metáfora" },
      { letter: "C", text: "Hipérbole" },
      { letter: "D", text: "Ironia" },
    ],
    correctAnswer: "B",
  },
  {
    id: 21,
    subject: "Matemática",
    topic: "Razão e Proporção",
    difficulty: "medium",
    banca: "FGV",
    year: 2023,
    cargo: "Auditor",
    instituicao: "CGU",
    title: "Regra de Três",
    text: "Se 5 operários constroem um muro em 8 dias, em quantos dias 10 operários construirão o mesmo muro?",
    options: [
      { letter: "A", text: "16 dias" },
      { letter: "B", text: "4 dias" },
      { letter: "C", text: "10 dias" },
      { letter: "D", text: "2 dias" },
    ],
    correctAnswer: "B",
  },
  {
    id: 22,
    subject: "Raciocínio Lógico",
    topic: "Conjuntos",
    difficulty: "medium",
    banca: "CESPE",
    year: 2022,
    cargo: "Técnico",
    instituicao: "BACEN",
    title: "Operações com Conjuntos",
    text: "Se A = {1, 2, 3} e B = {2, 3, 4}, qual é A ∩ B?",
    options: [
      { letter: "A", text: "{1, 2, 3, 4}" },
      { letter: "B", text: "{2, 3}" },
      { letter: "C", text: "{1, 4}" },
      { letter: "D", text: "{1}" },
    ],
    correctAnswer: "B",
  },
  {
    id: 23,
    subject: "Direito Trabalhista",
    topic: "CLT",
    difficulty: "medium",
    banca: "FCC",
    year: 2023,
    cargo: "Analista",
    instituicao: "TRT",
    title: "Férias",
    text: "Após quantos meses de trabalho o empregado adquire direito a férias?",
    options: [
      { letter: "A", text: "6 meses" },
      { letter: "B", text: "12 meses" },
      { letter: "C", text: "18 meses" },
      { letter: "D", text: "24 meses" },
    ],
    correctAnswer: "B",
  },
  {
    id: 24,
    subject: "Geografia",
    topic: "Geopolítica",
    difficulty: "hard",
    banca: "VUNESP",
    year: 2022,
    cargo: "Diplomata",
    instituicao: "MRE",
    title: "BRICS",
    text: "Quais países formavam originalmente o grupo BRICS?",
    options: [
      { letter: "A", text: "Brasil, Rússia, Índia, China e África do Sul" },
      { letter: "B", text: "Brasil, Rússia, Itália, China e Suíça" },
      { letter: "C", text: "Bolívia, Rússia, Índia, Canadá e Suécia" },
      { letter: "D", text: "Brasil, Romênia, Irlanda, China e Sérvia" },
    ],
    correctAnswer: "A",
  },
  {
    id: 25,
    subject: "Informática",
    topic: "Internet",
    difficulty: "easy",
    banca: "CESPE",
    year: 2023,
    cargo: "Assistente",
    instituicao: "ANATEL",
    title: "Navegadores",
    text: "Qual destes NÃO é um navegador de internet?",
    options: [
      { letter: "A", text: "Google Chrome" },
      { letter: "B", text: "Mozilla Firefox" },
      { letter: "C", text: "Microsoft Excel" },
      { letter: "D", text: "Microsoft Edge" },
    ],
    correctAnswer: "C",
  },
  {
    id: 26,
    subject: "Português",
    topic: "Acentuação",
    difficulty: "easy",
    banca: "FGV",
    year: 2022,
    cargo: "Técnico",
    instituicao: "SEFAZ",
    title: "Regras de Acentuação",
    text: "Qual palavra é acentuada por ser proparoxítona?",
    options: [
      { letter: "A", text: "Café" },
      { letter: "B", text: "Lâmpada" },
      { letter: "C", text: "Táxi" },
      { letter: "D", text: "Você" },
    ],
    correctAnswer: "B",
  },
  {
    id: 27,
    subject: "Matemática",
    topic: "Estatística",
    difficulty: "medium",
    banca: "FCC",
    year: 2023,
    cargo: "Estatístico",
    instituicao: "IBGE",
    title: "Média Aritmética",
    text: "Qual a média aritmética de 4, 6, 8, 10 e 12?",
    options: [
      { letter: "A", text: "7" },
      { letter: "B", text: "8" },
      { letter: "C", text: "9" },
      { letter: "D", text: "10" },
    ],
    correctAnswer: "B",
  },
  {
    id: 28,
    subject: "Direito Civil",
    topic: "Pessoas",
    difficulty: "medium",
    banca: "CESPE",
    year: 2022,
    cargo: "Juiz",
    instituicao: "TJ",
    title: "Capacidade Civil",
    text: "A capacidade civil plena é adquirida aos:",
    options: [
      { letter: "A", text: "16 anos" },
      { letter: "B", text: "18 anos" },
      { letter: "C", text: "21 anos" },
      { letter: "D", text: "25 anos" },
    ],
    correctAnswer: "B",
  },
  {
    id: 29,
    subject: "História",
    topic: "Brasil Colônia",
    difficulty: "easy",
    banca: "VUNESP",
    year: 2023,
    cargo: "Professor",
    instituicao: "SEDUC",
    title: "Descobrimento",
    text: "Quem comandou a expedição que chegou ao Brasil em 1500?",
    options: [
      { letter: "A", text: "Cristóvão Colombo" },
      { letter: "B", text: "Pedro Álvares Cabral" },
      { letter: "C", text: "Vasco da Gama" },
      { letter: "D", text: "Fernão de Magalhães" },
    ],
    correctAnswer: "B",
  },
  {
    id: 30,
    subject: "Raciocínio Lógico",
    topic: "Probabilidade",
    difficulty: "hard",
    banca: "FGV",
    year: 2022,
    cargo: "Analista",
    instituicao: "BNDES",
    title: "Cálculo de Probabilidade",
    text: "Qual a probabilidade de obter cara ao lançar uma moeda honesta duas vezes consecutivas?",
    options: [
      { letter: "A", text: "1/2" },
      { letter: "B", text: "1/4" },
      { letter: "C", text: "3/4" },
      { letter: "D", text: "1/3" },
    ],
    correctAnswer: "B",
  },
  // ===== FÍSICA =====
  {
    id: 31, subject: "Física", topic: "Cinemática", difficulty: "easy", banca: "FCC", year: 2023, cargo: "Técnico", instituicao: "IF",
    title: "Velocidade Média",
    text: "Um carro percorre 120 km em 2 horas. Qual sua velocidade média?",
    options: [{ letter: "A", text: "40 km/h" }, { letter: "B", text: "60 km/h" }, { letter: "C", text: "80 km/h" }, { letter: "D", text: "100 km/h" }],
    correctAnswer: "B",
  },
  {
    id: 32, subject: "Física", topic: "Cinemática", difficulty: "medium", banca: "CESPE", year: 2022, cargo: "Analista", instituicao: "INMETRO",
    title: "Queda Livre",
    text: "Um objeto é solto do repouso e cai em queda livre. Após 3 segundos, qual sua velocidade? (g = 10 m/s²)",
    options: [{ letter: "A", text: "10 m/s" }, { letter: "B", text: "20 m/s" }, { letter: "C", text: "30 m/s" }, { letter: "D", text: "40 m/s" }],
    correctAnswer: "C",
  },
  {
    id: 33, subject: "Física", topic: "Dinâmica", difficulty: "medium", banca: "FGV", year: 2023, cargo: "Engenheiro", instituicao: "CREA",
    title: "Segunda Lei de Newton",
    text: "Uma força de 20 N é aplicada a um corpo de 4 kg. Qual a aceleração?",
    options: [{ letter: "A", text: "2 m/s²" }, { letter: "B", text: "5 m/s²" }, { letter: "C", text: "8 m/s²" }, { letter: "D", text: "10 m/s²" }],
    correctAnswer: "B",
  },
  {
    id: 34, subject: "Física", topic: "Dinâmica", difficulty: "easy", banca: "VUNESP", year: 2022, cargo: "Professor", instituicao: "SEE-SP",
    title: "Peso de um Corpo",
    text: "Qual o peso de um corpo de massa 5 kg na superfície da Terra? (g = 10 m/s²)",
    options: [{ letter: "A", text: "5 N" }, { letter: "B", text: "50 N" }, { letter: "C", text: "500 N" }, { letter: "D", text: "0,5 N" }],
    correctAnswer: "B",
  },
  {
    id: 35, subject: "Física", topic: "Termodinâmica", difficulty: "easy", banca: "FCC", year: 2023, cargo: "Técnico", instituicao: "CNEN",
    title: "Escalas Termométricas",
    text: "Qual a temperatura de ebulição da água em Celsius ao nível do mar?",
    options: [{ letter: "A", text: "0 °C" }, { letter: "B", text: "50 °C" }, { letter: "C", text: "100 °C" }, { letter: "D", text: "212 °C" }],
    correctAnswer: "C",
  },
  {
    id: 36, subject: "Física", topic: "Termodinâmica", difficulty: "medium", banca: "CESPE", year: 2022, cargo: "Analista", instituicao: "ANP",
    title: "Conversão de Temperatura",
    text: "Converta 77 °F para Celsius:",
    options: [{ letter: "A", text: "15 °C" }, { letter: "B", text: "25 °C" }, { letter: "C", text: "35 °C" }, { letter: "D", text: "45 °C" }],
    correctAnswer: "B",
  },
  {
    id: 37, subject: "Física", topic: "Óptica", difficulty: "easy", banca: "FGV", year: 2023, cargo: "Professor", instituicao: "SME",
    title: "Reflexão da Luz",
    text: "Na reflexão da luz, o ângulo de incidência é igual ao ângulo de:",
    options: [{ letter: "A", text: "Refração" }, { letter: "B", text: "Reflexão" }, { letter: "C", text: "Difração" }, { letter: "D", text: "Dispersão" }],
    correctAnswer: "B",
  },
  {
    id: 38, subject: "Física", topic: "Eletricidade", difficulty: "medium", banca: "VUNESP", year: 2022, cargo: "Engenheiro", instituicao: "CPFL",
    title: "Lei de Ohm",
    text: "Um resistor de 10 Ω é submetido a uma tensão de 20 V. Qual a corrente?",
    options: [{ letter: "A", text: "0,5 A" }, { letter: "B", text: "2 A" }, { letter: "C", text: "5 A" }, { letter: "D", text: "200 A" }],
    correctAnswer: "B",
  },
  {
    id: 39, subject: "Física", topic: "Eletricidade", difficulty: "hard", banca: "CESPE", year: 2023, cargo: "Analista", instituicao: "ANEEL",
    title: "Potência Elétrica",
    text: "Um chuveiro de 5500 W ligado em 220 V consome qual corrente?",
    options: [{ letter: "A", text: "10 A" }, { letter: "B", text: "25 A" }, { letter: "C", text: "50 A" }, { letter: "D", text: "15 A" }],
    correctAnswer: "B",
  },
  {
    id: 40, subject: "Física", topic: "Ondulatória", difficulty: "medium", banca: "FCC", year: 2022, cargo: "Técnico", instituicao: "INPE",
    title: "Velocidade do Som",
    text: "A velocidade do som no ar, em condições normais, é aproximadamente:",
    options: [{ letter: "A", text: "120 m/s" }, { letter: "B", text: "340 m/s" }, { letter: "C", text: "500 m/s" }, { letter: "D", text: "1000 m/s" }],
    correctAnswer: "B",
  },
  {
    id: 41, subject: "Física", topic: "Gravitação", difficulty: "hard", banca: "FGV", year: 2023, cargo: "Analista", instituicao: "AEB",
    title: "Leis de Kepler",
    text: "A terceira lei de Kepler relaciona:",
    options: [{ letter: "A", text: "Massa e velocidade" }, { letter: "B", text: "Período orbital e raio médio da órbita" }, { letter: "C", text: "Força e aceleração" }, { letter: "D", text: "Temperatura e pressão" }],
    correctAnswer: "B",
  },
  {
    id: 42, subject: "Física", topic: "Energia", difficulty: "easy", banca: "CESPE", year: 2022, cargo: "Técnico", instituicao: "ELETROBRAS",
    title: "Energia Cinética",
    text: "A energia cinética de um corpo depende de sua massa e de sua:",
    options: [{ letter: "A", text: "Posição" }, { letter: "B", text: "Velocidade" }, { letter: "C", text: "Temperatura" }, { letter: "D", text: "Cor" }],
    correctAnswer: "B",
  },
  {
    id: 43, subject: "Física", topic: "Hidrostática", difficulty: "medium", banca: "VUNESP", year: 2023, cargo: "Engenheiro", instituicao: "SABESP",
    title: "Pressão Atmosférica",
    text: "A pressão atmosférica ao nível do mar é aproximadamente:",
    options: [{ letter: "A", text: "1 atm" }, { letter: "B", text: "2 atm" }, { letter: "C", text: "0,5 atm" }, { letter: "D", text: "10 atm" }],
    correctAnswer: "A",
  },
  {
    id: 44, subject: "Física", topic: "Magnetismo", difficulty: "easy", banca: "FCC", year: 2022, cargo: "Professor", instituicao: "SEDUC",
    title: "Ímãs",
    text: "Os polos de um ímã são chamados de:",
    options: [{ letter: "A", text: "Positivo e negativo" }, { letter: "B", text: "Norte e sul" }, { letter: "C", text: "Leste e oeste" }, { letter: "D", text: "Superior e inferior" }],
    correctAnswer: "B",
  },
  {
    id: 45, subject: "Física", topic: "Física Nuclear", difficulty: "hard", banca: "CESPE", year: 2023, cargo: "Analista", instituicao: "CNEN",
    title: "Fissão Nuclear",
    text: "Na fissão nuclear, ocorre a:",
    options: [{ letter: "A", text: "União de núcleos leves" }, { letter: "B", text: "Divisão de núcleos pesados" }, { letter: "C", text: "Emissão de ondas de rádio" }, { letter: "D", text: "Absorção de nêutrons sem reação" }],
    correctAnswer: "B",
  },
  {
    id: 46, subject: "Física", topic: "MRU", difficulty: "easy", banca: "FGV", year: 2022, cargo: "Assistente", instituicao: "DETRAN",
    title: "Movimento Uniforme",
    text: "No MRU, a velocidade do corpo é:",
    options: [{ letter: "A", text: "Crescente" }, { letter: "B", text: "Constante" }, { letter: "C", text: "Decrescente" }, { letter: "D", text: "Nula" }],
    correctAnswer: "B",
  },
  // ===== QUÍMICA =====
  {
    id: 47, subject: "Química", topic: "Tabela Periódica", difficulty: "easy", banca: "FCC", year: 2023, cargo: "Técnico", instituicao: "FIOCRUZ",
    title: "Elementos Químicos",
    text: "Qual o símbolo químico do ouro?",
    options: [{ letter: "A", text: "Ag" }, { letter: "B", text: "Au" }, { letter: "C", text: "Fe" }, { letter: "D", text: "Cu" }],
    correctAnswer: "B",
  },
  {
    id: 48, subject: "Química", topic: "Ligações Químicas", difficulty: "medium", banca: "CESPE", year: 2022, cargo: "Analista", instituicao: "ANVISA",
    title: "Ligação Iônica",
    text: "A ligação iônica ocorre entre:",
    options: [{ letter: "A", text: "Dois metais" }, { letter: "B", text: "Metal e não-metal" }, { letter: "C", text: "Dois não-metais" }, { letter: "D", text: "Dois gases nobres" }],
    correctAnswer: "B",
  },
  {
    id: 49, subject: "Química", topic: "Reações Químicas", difficulty: "easy", banca: "FGV", year: 2023, cargo: "Professor", instituicao: "SME",
    title: "Balanceamento",
    text: "Na reação 2H₂ + O₂ → 2H₂O, o produto formado é:",
    options: [{ letter: "A", text: "Oxigênio" }, { letter: "B", text: "Água" }, { letter: "C", text: "Hidrogênio" }, { letter: "D", text: "Peróxido" }],
    correctAnswer: "B",
  },
  {
    id: 50, subject: "Química", topic: "Ácidos e Bases", difficulty: "easy", banca: "VUNESP", year: 2022, cargo: "Técnico", instituicao: "CETESB",
    title: "pH Neutro",
    text: "O pH neutro em solução aquosa a 25°C é:",
    options: [{ letter: "A", text: "0" }, { letter: "B", text: "7" }, { letter: "C", text: "14" }, { letter: "D", text: "1" }],
    correctAnswer: "B",
  },
  {
    id: 51, subject: "Química", topic: "Soluções", difficulty: "medium", banca: "FCC", year: 2023, cargo: "Analista", instituicao: "SABESP",
    title: "Concentração",
    text: "Se dissolvermos 10 g de sal em 90 g de água, a concentração em massa será:",
    options: [{ letter: "A", text: "5%" }, { letter: "B", text: "10%" }, { letter: "C", text: "15%" }, { letter: "D", text: "20%" }],
    correctAnswer: "B",
  },
  {
    id: 52, subject: "Química", topic: "Estequiometria", difficulty: "hard", banca: "CESPE", year: 2022, cargo: "Analista", instituicao: "ANA",
    title: "Mol",
    text: "Quantas moléculas existem em 1 mol de qualquer substância?",
    options: [{ letter: "A", text: "6,02 × 10²³" }, { letter: "B", text: "3,01 × 10²³" }, { letter: "C", text: "6,02 × 10²²" }, { letter: "D", text: "1,0 × 10²⁴" }],
    correctAnswer: "A",
  },
  {
    id: 53, subject: "Química", topic: "Química Orgânica", difficulty: "medium", banca: "FGV", year: 2023, cargo: "Analista", instituicao: "PETROBRAS",
    title: "Hidrocarbonetos",
    text: "O metano (CH₄) é classificado como:",
    options: [{ letter: "A", text: "Alceno" }, { letter: "B", text: "Alcano" }, { letter: "C", text: "Alcino" }, { letter: "D", text: "Aromático" }],
    correctAnswer: "B",
  },
  {
    id: 54, subject: "Química", topic: "Termoquímica", difficulty: "medium", banca: "VUNESP", year: 2022, cargo: "Engenheiro", instituicao: "UNESP",
    title: "Reação Exotérmica",
    text: "Uma reação exotérmica é aquela que:",
    options: [{ letter: "A", text: "Absorve calor" }, { letter: "B", text: "Libera calor" }, { letter: "C", text: "Não troca calor" }, { letter: "D", text: "Absorve luz" }],
    correctAnswer: "B",
  },
  {
    id: 55, subject: "Química", topic: "Eletroquímica", difficulty: "hard", banca: "CESPE", year: 2023, cargo: "Analista", instituicao: "CPRM",
    title: "Pilhas",
    text: "Em uma pilha eletroquímica, a oxidação ocorre no:",
    options: [{ letter: "A", text: "Cátodo" }, { letter: "B", text: "Ânodo" }, { letter: "C", text: "Eletrólito" }, { letter: "D", text: "Fio condutor" }],
    correctAnswer: "B",
  },
  {
    id: 56, subject: "Química", topic: "Gases", difficulty: "medium", banca: "FCC", year: 2022, cargo: "Técnico", instituicao: "PETROBRAS",
    title: "Lei dos Gases",
    text: "A temperatura absoluta zero (0 K) corresponde a:",
    options: [{ letter: "A", text: "0 °C" }, { letter: "B", text: "-273 °C" }, { letter: "C", text: "-100 °C" }, { letter: "D", text: "100 °C" }],
    correctAnswer: "B",
  },
  {
    id: 57, subject: "Química", topic: "Radioatividade", difficulty: "hard", banca: "FGV", year: 2023, cargo: "Analista", instituicao: "CNEN",
    title: "Partículas Alfa",
    text: "A partícula alfa é constituída por:",
    options: [{ letter: "A", text: "2 elétrons" }, { letter: "B", text: "2 prótons e 2 nêutrons" }, { letter: "C", text: "1 próton e 1 nêutron" }, { letter: "D", text: "Apenas nêutrons" }],
    correctAnswer: "B",
  },
  {
    id: 58, subject: "Química", topic: "Cinética Química", difficulty: "medium", banca: "VUNESP", year: 2022, cargo: "Professor", instituicao: "UNICAMP",
    title: "Catalisador",
    text: "Um catalisador atua em uma reação química:",
    options: [{ letter: "A", text: "Aumentando o produto" }, { letter: "B", text: "Diminuindo a energia de ativação" }, { letter: "C", text: "Aumentando a temperatura" }, { letter: "D", text: "Adicionando reagentes" }],
    correctAnswer: "B",
  },
  {
    id: 59, subject: "Química", topic: "Tabela Periódica", difficulty: "easy", banca: "CESPE", year: 2023, cargo: "Assistente", instituicao: "IBAMA",
    title: "Gases Nobres",
    text: "Qual destes é um gás nobre?",
    options: [{ letter: "A", text: "Oxigênio" }, { letter: "B", text: "Hélio" }, { letter: "C", text: "Nitrogênio" }, { letter: "D", text: "Hidrogênio" }],
    correctAnswer: "B",
  },
  {
    id: 60, subject: "Química", topic: "Química Ambiental", difficulty: "easy", banca: "FCC", year: 2022, cargo: "Técnico", instituicao: "CETESB",
    title: "Camada de Ozônio",
    text: "A fórmula do ozônio é:",
    options: [{ letter: "A", text: "O₂" }, { letter: "B", text: "O₃" }, { letter: "C", text: "CO₂" }, { letter: "D", text: "H₂O" }],
    correctAnswer: "B",
  },
  {
    id: 61, subject: "Química", topic: "Funções Inorgânicas", difficulty: "medium", banca: "FGV", year: 2023, cargo: "Técnico", instituicao: "SEFAZ",
    title: "Ácidos",
    text: "O HCl é classificado como:",
    options: [{ letter: "A", text: "Base" }, { letter: "B", text: "Ácido" }, { letter: "C", text: "Sal" }, { letter: "D", text: "Óxido" }],
    correctAnswer: "B",
  },
  {
    id: 62, subject: "Química", topic: "Modelos Atômicos", difficulty: "easy", banca: "CESPE", year: 2022, cargo: "Professor", instituicao: "SEE",
    title: "Modelo de Bohr",
    text: "No modelo atômico de Bohr, os elétrons se movem em:",
    options: [{ letter: "A", text: "Linhas retas" }, { letter: "B", text: "Órbitas definidas" }, { letter: "C", text: "Nuvens aleatórias" }, { letter: "D", text: "Espirais" }],
    correctAnswer: "B",
  },
  // ===== BIOLOGIA =====
  {
    id: 63, subject: "Biologia", topic: "Citologia", difficulty: "easy", banca: "FCC", year: 2023, cargo: "Técnico", instituicao: "FIOCRUZ",
    title: "Célula",
    text: "A organela responsável pela respiração celular é:",
    options: [{ letter: "A", text: "Ribossomo" }, { letter: "B", text: "Mitocôndria" }, { letter: "C", text: "Complexo de Golgi" }, { letter: "D", text: "Lisossomo" }],
    correctAnswer: "B",
  },
  {
    id: 64, subject: "Biologia", topic: "Genética", difficulty: "medium", banca: "CESPE", year: 2022, cargo: "Analista", instituicao: "EMBRAPA",
    title: "DNA",
    text: "As bases nitrogenadas do DNA são:",
    options: [{ letter: "A", text: "A, U, C, G" }, { letter: "B", text: "A, T, C, G" }, { letter: "C", text: "A, T, C, U" }, { letter: "D", text: "A, G, U, T" }],
    correctAnswer: "B",
  },
  {
    id: 65, subject: "Biologia", topic: "Ecologia", difficulty: "easy", banca: "FGV", year: 2023, cargo: "Analista", instituicao: "IBAMA",
    title: "Cadeia Alimentar",
    text: "Na cadeia alimentar, os produtores são geralmente:",
    options: [{ letter: "A", text: "Animais herbívoros" }, { letter: "B", text: "Plantas e algas" }, { letter: "C", text: "Fungos" }, { letter: "D", text: "Bactérias decompositoras" }],
    correctAnswer: "B",
  },
  {
    id: 66, subject: "Biologia", topic: "Evolução", difficulty: "medium", banca: "VUNESP", year: 2022, cargo: "Professor", instituicao: "USP",
    title: "Seleção Natural",
    text: "A teoria da seleção natural foi proposta por:",
    options: [{ letter: "A", text: "Lamarck" }, { letter: "B", text: "Darwin" }, { letter: "C", text: "Mendel" }, { letter: "D", text: "Pasteur" }],
    correctAnswer: "B",
  },
  {
    id: 67, subject: "Biologia", topic: "Botânica", difficulty: "easy", banca: "FCC", year: 2023, cargo: "Técnico", instituicao: "EMBRAPA",
    title: "Fotossíntese",
    text: "A fotossíntese ocorre nos:",
    options: [{ letter: "A", text: "Ribossomos" }, { letter: "B", text: "Cloroplastos" }, { letter: "C", text: "Lisossomos" }, { letter: "D", text: "Vacúolos" }],
    correctAnswer: "B",
  },
  {
    id: 68, subject: "Biologia", topic: "Fisiologia Humana", difficulty: "easy", banca: "CESPE", year: 2022, cargo: "Técnico", instituicao: "MS",
    title: "Sistema Circulatório",
    text: "O órgão central do sistema circulatório humano é:",
    options: [{ letter: "A", text: "Pulmão" }, { letter: "B", text: "Coração" }, { letter: "C", text: "Fígado" }, { letter: "D", text: "Rim" }],
    correctAnswer: "B",
  },
  {
    id: 69, subject: "Biologia", topic: "Microbiologia", difficulty: "medium", banca: "FGV", year: 2023, cargo: "Analista", instituicao: "ANVISA",
    title: "Vírus",
    text: "Os vírus são considerados:",
    options: [{ letter: "A", text: "Seres vivos celulares" }, { letter: "B", text: "Parasitas intracelulares obrigatórios" }, { letter: "C", text: "Bactérias pequenas" }, { letter: "D", text: "Fungos microscópicos" }],
    correctAnswer: "B",
  },
  {
    id: 70, subject: "Biologia", topic: "Genética", difficulty: "hard", banca: "VUNESP", year: 2022, cargo: "Biólogo", instituicao: "FAPESP",
    title: "Leis de Mendel",
    text: "Na primeira lei de Mendel, os fatores (genes) se separam durante a formação dos:",
    options: [{ letter: "A", text: "Zigoto" }, { letter: "B", text: "Gametas" }, { letter: "C", text: "Blástula" }, { letter: "D", text: "Tecidos" }],
    correctAnswer: "B",
  },
  {
    id: 71, subject: "Biologia", topic: "Zoologia", difficulty: "easy", banca: "FCC", year: 2023, cargo: "Professor", instituicao: "SEDUC",
    title: "Vertebrados",
    text: "Qual destes animais é um mamífero?",
    options: [{ letter: "A", text: "Jacaré" }, { letter: "B", text: "Baleia" }, { letter: "C", text: "Tubarão" }, { letter: "D", text: "Tartaruga" }],
    correctAnswer: "B",
  },
  {
    id: 72, subject: "Biologia", topic: "Ecologia", difficulty: "medium", banca: "CESPE", year: 2022, cargo: "Analista", instituicao: "ICMBio",
    title: "Biomas",
    text: "O bioma brasileiro com maior biodiversidade é:",
    options: [{ letter: "A", text: "Cerrado" }, { letter: "B", text: "Amazônia" }, { letter: "C", text: "Caatinga" }, { letter: "D", text: "Pampa" }],
    correctAnswer: "B",
  },
  {
    id: 73, subject: "Biologia", topic: "Bioquímica", difficulty: "medium", banca: "FGV", year: 2023, cargo: "Analista", instituicao: "FIOCRUZ",
    title: "Proteínas",
    text: "As proteínas são formadas por unidades chamadas:",
    options: [{ letter: "A", text: "Nucleotídeos" }, { letter: "B", text: "Aminoácidos" }, { letter: "C", text: "Monossacarídeos" }, { letter: "D", text: "Ácidos graxos" }],
    correctAnswer: "B",
  },
  {
    id: 74, subject: "Biologia", topic: "Fisiologia Humana", difficulty: "medium", banca: "VUNESP", year: 2022, cargo: "Enfermeiro", instituicao: "SUS",
    title: "Sistema Nervoso",
    text: "O principal órgão do sistema nervoso central é:",
    options: [{ letter: "A", text: "Medula espinhal" }, { letter: "B", text: "Encéfalo" }, { letter: "C", text: "Nervo vago" }, { letter: "D", text: "Gânglio" }],
    correctAnswer: "B",
  },
  {
    id: 75, subject: "Biologia", topic: "Imunologia", difficulty: "medium", banca: "CESPE", year: 2023, cargo: "Analista", instituicao: "MS",
    title: "Vacinas",
    text: "As vacinas atuam estimulando o sistema:",
    options: [{ letter: "A", text: "Digestório" }, { letter: "B", text: "Imunológico" }, { letter: "C", text: "Endócrino" }, { letter: "D", text: "Muscular" }],
    correctAnswer: "B",
  },
  {
    id: 76, subject: "Biologia", topic: "Citologia", difficulty: "medium", banca: "FCC", year: 2022, cargo: "Biólogo", instituicao: "BUTANTAN",
    title: "Célula Procarionte",
    text: "A principal diferença entre célula procarionte e eucarionte é a ausência de:",
    options: [{ letter: "A", text: "Ribossomos" }, { letter: "B", text: "Núcleo organizado" }, { letter: "C", text: "Membrana plasmática" }, { letter: "D", text: "DNA" }],
    correctAnswer: "B",
  },
  {
    id: 77, subject: "Biologia", topic: "Ecologia", difficulty: "hard", banca: "FGV", year: 2023, cargo: "Analista", instituicao: "IBAMA",
    title: "Efeito Estufa",
    text: "O principal gás responsável pelo efeito estufa é:",
    options: [{ letter: "A", text: "Oxigênio" }, { letter: "B", text: "Dióxido de carbono" }, { letter: "C", text: "Nitrogênio" }, { letter: "D", text: "Hélio" }],
    correctAnswer: "B",
  },
  {
    id: 78, subject: "Biologia", topic: "Fisiologia Humana", difficulty: "easy", banca: "VUNESP", year: 2022, cargo: "Técnico", instituicao: "HCFMUSP",
    title: "Tipos Sanguíneos",
    text: "O doador universal de hemácias é o tipo sanguíneo:",
    options: [{ letter: "A", text: "A" }, { letter: "B", text: "O negativo" }, { letter: "C", text: "AB" }, { letter: "D", text: "B positivo" }],
    correctAnswer: "B",
  },
  {
    id: 79, subject: "Biologia", topic: "Taxonomia", difficulty: "easy", banca: "CESPE", year: 2023, cargo: "Professor", instituicao: "UnB",
    title: "Reinos",
    text: "Os fungos pertencem ao reino:",
    options: [{ letter: "A", text: "Plantae" }, { letter: "B", text: "Fungi" }, { letter: "C", text: "Protista" }, { letter: "D", text: "Monera" }],
    correctAnswer: "B",
  },
  {
    id: 80, subject: "Biologia", topic: "Genética", difficulty: "hard", banca: "FCC", year: 2022, cargo: "Biólogo", instituicao: "USP",
    title: "Mutação",
    text: "As mutações genéticas são alterações na sequência de:",
    options: [{ letter: "A", text: "Proteínas" }, { letter: "B", text: "Nucleotídeos do DNA" }, { letter: "C", text: "Lipídios" }, { letter: "D", text: "Carboidratos" }],
    correctAnswer: "B",
  },
];

export const getQuestionsBySubject = (subject: string, count: number): Question[] => {
  let filtered = subject === "Todas" 
    ? [...sampleQuestions] 
    : sampleQuestions.filter(q => q.subject === subject);
  
  // Shuffle and return requested count
  const shuffled = filtered.sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
};

export const calculateXP = (isCorrect: boolean, confidence: "certeza" | "duvida" | "chute"): number => {
  if (!isCorrect) return 0;
  
  switch (confidence) {
    case "certeza": return 5;
    case "duvida": return 3;
    case "chute": return 1;
    default: return 0;
  }
};
